/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame, useThree } from "@react-three/fiber";

type GLTFResult = GLTF & {
 nodes: {
  Torus: THREE.Mesh;
  Torus001: THREE.Mesh;
  Torus002: THREE.Mesh;
  Cylinder: THREE.Mesh;
  Cylinder001: THREE.Mesh;
  Cylinder002: THREE.Mesh;
  Cylinder003: THREE.Mesh;
  Cylinder004: THREE.Mesh;
  Cylinder005: THREE.Mesh;
  Cylinder006: THREE.Mesh;
  Cylinder007: THREE.Mesh;
  Cube: THREE.Mesh;
  Cube001: THREE.Mesh;
  Cube002: THREE.Mesh;
  Cube003: THREE.Mesh;
  Cube004: THREE.Mesh;
  Cube005: THREE.Mesh;
  Cube006: THREE.Mesh;
  Cube007: THREE.Mesh;
  Cube008: THREE.Mesh;
  Cube009: THREE.Mesh;
  Cube010: THREE.Mesh;
 };
 materials: {
  ["Material.001"]: THREE.MeshStandardMaterial;
 };
};

export default function IntroModel(props: JSX.IntrinsicElements["group"]) {
 const { nodes, materials } = useGLTF("/3d/intro-model.glb") as GLTFResult;
 const grillRef = useRef<THREE.Group>(null);
 const modelRef = useRef<THREE.Group>(null);
 const { pointer } = useThree();
 useFrame((state, delta) => {
  const x = pointer.x / window.innerWidth;
  const y = pointer.y / window.innerHeight;
  if (modelRef.current) {
   modelRef.current.rotation.x = x*100;
   modelRef.current.rotation.y = y*100;
  }
  if (grillRef.current) {
   grillRef.current.rotation.y += delta / 10;
  }
 });
 return (
  <group {...props} dispose={null}>
   <group name="Scene" ref={modelRef}>
    <group name="Gril" ref={grillRef}>
     <mesh
      name="Torus"
      castShadow
      receiveShadow
      geometry={nodes.Torus.geometry}
      material={nodes.Torus.material}
     />
     <mesh
      name="Torus001"
      castShadow
      receiveShadow
      geometry={nodes.Torus001.geometry}
      material={nodes.Torus001.material}
      scale={1.495}
     />
     <mesh
      name="Torus002"
      castShadow
      receiveShadow
      geometry={nodes.Torus002.geometry}
      material={nodes.Torus002.material}
      scale={2.455}
     />
     <mesh
      name="Cylinder"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder.geometry}
      material={materials["Material.001"]}
      rotation={[-1.572, 0, 0]}
      scale={[0.013, 2.794, 0.013]}
     />
     <mesh
      name="Cylinder001"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder001.geometry}
      material={nodes.Cylinder001.material}
      rotation={[-1.571, -0.001, 0.785]}
      scale={[0.013, 2.794, 0.013]}
     />
     <mesh
      name="Cylinder002"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder002.geometry}
      material={nodes.Cylinder002.material}
      rotation={[-Math.PI / 2, -0.001, 1.571]}
      scale={[0.013, 2.794, 0.013]}
     />
     <mesh
      name="Cylinder003"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder003.geometry}
      material={nodes.Cylinder003.material}
      rotation={[-1.57, -0.001, 2.354]}
      scale={[0.013, 2.794, 0.013]}
     />
     <mesh
      name="Cylinder004"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder004.geometry}
      material={nodes.Cylinder004.material}
      position={[0, 0, -1.051]}
      rotation={[-Math.PI / 2, -0.001, 1.571]}
      scale={[0.013, 2.794, 0.013]}
     />
     <mesh
      name="Cylinder005"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder005.geometry}
      material={nodes.Cylinder005.material}
      position={[0, 0, 1.045]}
      rotation={[-Math.PI / 2, -0.001, 1.571]}
      scale={[0.013, 2.794, 0.013]}
     />
     <mesh
      name="Cylinder006"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder006.geometry}
      material={nodes.Cylinder006.material}
      position={[-1.051, 0, 0]}
      rotation={[-1.572, 0, 0]}
      scale={[0.013, 2.794, 0.013]}
     />
     <mesh
      name="Cylinder007"
      castShadow
      receiveShadow
      geometry={nodes.Cylinder007.geometry}
      material={nodes.Cylinder007.material}
      position={[1.051, 0, 0]}
      rotation={[-1.572, 0, 0]}
      scale={[0.013, 2.794, 0.013]}
     />
    </group>
    <mesh
     name="Cube"
     castShadow
     receiveShadow
     geometry={nodes.Cube.geometry}
     material={nodes.Cube.material}
     position={[-1.429, 0, -2.61]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube001"
     castShadow
     receiveShadow
     geometry={nodes.Cube001.geometry}
     material={nodes.Cube001.material}
     position={[-0.685, 0, -1.126]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube002"
     castShadow
     receiveShadow
     geometry={nodes.Cube002.geometry}
     material={nodes.Cube002.material}
     position={[-0.005, 0, -2.173]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube003"
     castShadow
     receiveShadow
     geometry={nodes.Cube003.geometry}
     material={nodes.Cube003.material}
     position={[-1.695, 0, -0.398]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube004"
     castShadow
     receiveShadow
     geometry={nodes.Cube004.geometry}
     material={nodes.Cube004.material}
     position={[-0.384, 0, 0.148]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube005"
     castShadow
     receiveShadow
     geometry={nodes.Cube005.geometry}
     material={nodes.Cube005.material}
     position={[0.59, 0, -0.671]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube006"
     castShadow
     receiveShadow
     geometry={nodes.Cube006.geometry}
     material={nodes.Cube006.material}
     position={[1.054, 0, 0.385]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube007"
     castShadow
     receiveShadow
     geometry={nodes.Cube007.geometry}
     material={nodes.Cube007.material}
     position={[-0.066, 0, 1.286]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube008"
     castShadow
     receiveShadow
     geometry={nodes.Cube008.geometry}
     material={nodes.Cube008.material}
     position={[-1.44, 0, 1.086]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube009"
     castShadow
     receiveShadow
     geometry={nodes.Cube009.geometry}
     material={nodes.Cube009.material}
     position={[0.344, 0, 2.551]}
     scale={[0.386, 0.029, 0.386]}
    />
    <mesh
     name="Cube010"
     castShadow
     receiveShadow
     geometry={nodes.Cube010.geometry}
     material={nodes.Cube010.material}
     position={[-1.823, 0, 2.551]}
     scale={[0.386, 0.029, 0.386]}
    />
   </group>
  </group>
 );
}

useGLTF.preload("/3d/intro-model.glb");
