/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame, useThree } from "@react-three/fiber";


type GLTFResult = GLTF & {
 nodes: {
  Cube: THREE.Mesh
  Cube001: THREE.Mesh
  Cube002: THREE.Mesh
  Cube003: THREE.Mesh
  Cube004: THREE.Mesh
  Cube005: THREE.Mesh
  Cube006: THREE.Mesh
  Cube007: THREE.Mesh
  Cube008: THREE.Mesh
  Cube009: THREE.Mesh
  Cube010: THREE.Mesh
  Curve001: THREE.Mesh
  Curve002: THREE.Mesh
  Curve003: THREE.Mesh
  Curve011_1: THREE.Mesh
  Curve011_2: THREE.Mesh
  Curve011_3: THREE.Mesh
  Curve012_1: THREE.Mesh
  Curve012_2: THREE.Mesh
  Curve012_3: THREE.Mesh
  Curve005: THREE.Mesh
  Curve006: THREE.Mesh
  Curve015_1: THREE.Mesh
  Curve015_2: THREE.Mesh
  Curve015_3: THREE.Mesh
  Curve018_1: THREE.Mesh
  Curve018_2: THREE.Mesh
  Curve018_3: THREE.Mesh
  Curve009: THREE.Mesh
  Curve010: THREE.Mesh
  Curve023_1: THREE.Mesh
  Curve023_2: THREE.Mesh
  Curve023_3: THREE.Mesh
  Curve024_1: THREE.Mesh
  Curve024_2: THREE.Mesh
  Curve024_3: THREE.Mesh
  Curve013: THREE.Mesh
  Curve015: THREE.Mesh
  Curve016: THREE.Mesh
  Curve018: THREE.Mesh
  Curve017: THREE.Mesh
  Curve019: THREE.Mesh
  Curve020: THREE.Mesh
  Curve022_1: THREE.Mesh
  Curve022_2: THREE.Mesh
  Curve022_3: THREE.Mesh
  Curve028_1: THREE.Mesh
  Curve028_2: THREE.Mesh
  Curve028_3: THREE.Mesh
  Curve016_1: THREE.Mesh
  Curve016_2: THREE.Mesh
  Curve016_3: THREE.Mesh
  Curve026_1: THREE.Mesh
  Curve026_2: THREE.Mesh
  Curve026_3: THREE.Mesh
  Curve025: THREE.Mesh
  Curve026: THREE.Mesh
  Curve027: THREE.Mesh
  Cube011: THREE.Mesh
  Cube012: THREE.Mesh
  Curve: THREE.Mesh
  Curve028: THREE.Mesh
  Curve029: THREE.Mesh
  Curve030: THREE.Mesh
 }
 materials: {
  ['React background']: THREE.MeshStandardMaterial
  ['Firebase background']: THREE.MeshStandardMaterial
  ['JS background']: THREE.MeshStandardMaterial
  ['Angular White']: THREE.MeshStandardMaterial
  ['Typescript background']: THREE.MeshStandardMaterial
  ['SVGMat.021']: THREE.MeshStandardMaterial
  ['Github background']: THREE.MeshStandardMaterial
  ['HTML5 Background']: THREE.MeshStandardMaterial
  ['React forground']: THREE.MeshStandardMaterial
  ['JS forground']: THREE.MeshStandardMaterial
  ['Firebase 1']: THREE.MeshStandardMaterial
  ['Firebase 3']: THREE.MeshStandardMaterial
  ['Firebase 2']: THREE.MeshStandardMaterial
  ['Pure white']: THREE.MeshStandardMaterial
  ['SVGMat.019']: THREE.MeshStandardMaterial
  ['SVGMat.020']: THREE.MeshStandardMaterial
  ['AWS forground']: THREE.MeshStandardMaterial
  ['SVGMat.025']: THREE.MeshStandardMaterial
  ['SVGMat.023']: THREE.MeshStandardMaterial
  ['SVGMat.024']: THREE.MeshStandardMaterial
  ['flutter sky blue']: THREE.MeshStandardMaterial
  ['flutter dark blue']: THREE.MeshStandardMaterial
  ['flutter medium blue']: THREE.MeshStandardMaterial
  ['flutter medium blue.001']: THREE.MeshStandardMaterial
  ['flutter dark blue.001']: THREE.MeshStandardMaterial
  ['flutter sky blue.001']: THREE.MeshStandardMaterial
  ['CSS White.001']: THREE.MeshStandardMaterial
  ['CSS color 2.001']: THREE.MeshStandardMaterial
  ['CSS color 1.001']: THREE.MeshStandardMaterial
  ['Angular red 2.001']: THREE.MeshStandardMaterial
  ['Angular red 1.001']: THREE.MeshStandardMaterial
  ['Angular White.001']: THREE.MeshStandardMaterial
  ['CSS White']: THREE.MeshStandardMaterial
  ['CSS color 2']: THREE.MeshStandardMaterial
  ['CSS color 1']: THREE.MeshStandardMaterial
  ['Angular red 2']: THREE.MeshStandardMaterial
  ['Angular red 1']: THREE.MeshStandardMaterial
  ['Material.001']: THREE.MeshStandardMaterial
  ['Material.002']: THREE.MeshStandardMaterial
  Golang: THREE.MeshStandardMaterial
  Nextjs: THREE.MeshStandardMaterial
 }
}

export default function IntroModel(props: JSX.IntrinsicElements["group"]) {
 const { nodes, materials } = useGLTF("/3d/intro-model-new.glb") as GLTFResult;
 const grillRef = useRef<THREE.Group>(null);
 const modelRef = useRef<THREE.Group>(null);
 const { pointer } = useThree();
 useFrame((state, delta) => {
  const x = pointer.x / window.innerWidth;
  const y = pointer.y / window.innerHeight;
  if (modelRef.current) {
   modelRef.current.rotation.x = x * 100;
   modelRef.current.rotation.y = y * 100;
  }
  if (grillRef.current) {
   grillRef.current.rotation.y += delta / 10;
  }
 });
 return (
  <group {...props} dispose={null}>
   <group name="Scene" ref={modelRef}>
    <mesh
     name="Cube"
     castShadow
     receiveShadow
     geometry={nodes.Cube.geometry}
     material={materials['React background']}
     position={[-1.4291, 0, -2.61012]}
     scale={[0.38596, 0.37041, 0.38596]}
    />
    <mesh
     name="Cube001"
     castShadow
     receiveShadow
     geometry={nodes.Cube001.geometry}
     material={materials['Firebase background']}
     position={[-0.68465, 0, -1.12636]}
     scale={[0.38596, 0.36813, 0.38596]}
    />
    <mesh
     name="Cube002"
     castShadow
     receiveShadow
     geometry={nodes.Cube002.geometry}
     material={materials['JS background']}
     position={[-0.00493, 0, -2.17297]}
     scale={[0.38596, 0.36928, 0.38596]}
    />
    <mesh
     name="Cube003"
     castShadow
     receiveShadow
     geometry={nodes.Cube003.geometry}
     material={materials['Angular White']}
     position={[-1.69506, 0, -0.39813]}
     scale={[0.38596, 0.36774, 0.38596]}
    />
    <mesh
     name="Cube004"
     castShadow
     receiveShadow
     geometry={nodes.Cube004.geometry}
     material={materials['Typescript background']}
     position={[-0.38425, 0, 0.14804]}
     scale={[0.38596, 0.36903, 0.38596]}
    />
    <mesh
     name="Cube005"
     castShadow
     receiveShadow
     geometry={nodes.Cube005.geometry}
     material={materials['React background']}
     position={[0.58975, 0, -0.67122]}
     scale={[0.38596, 0.36962, 0.38596]}
    />
    <mesh
     name="Cube006"
     castShadow
     receiveShadow
     geometry={nodes.Cube006.geometry}
     material={materials['SVGMat.021']}
     position={[1.054, 0, 0.38471]}
     scale={[0.38596, 0.36886, 0.38596]}
    />
    <mesh
     name="Cube007"
     castShadow
     receiveShadow
     geometry={nodes.Cube007.geometry}
     material={materials['Github background']}
     position={[-0.06565, 0, 1.28589]}
     scale={[0.38596, 0.36862, 0.38596]}
    />
    <mesh
     name="Cube008"
     castShadow
     receiveShadow
     geometry={nodes.Cube008.geometry}
     material={materials['React background']}
     position={[-1.44018, 0, 1.08563]}
     scale={[0.38596, 0.36912, 0.38596]}
    />
    <mesh
     name="Cube009"
     castShadow
     receiveShadow
     geometry={nodes.Cube009.geometry}
     material={materials['React background']}
     position={[0.34398, 0, 2.55119]}
     scale={[0.38596, 0.3679, 0.38596]}
    />
    <mesh
     name="Cube010"
     castShadow
     receiveShadow
     geometry={nodes.Cube010.geometry}
     material={materials['HTML5 Background']}
     position={[-1.8225, 0, 2.55119]}
     scale={[0.38596, 0.36939, 0.38596]}
    />
    <mesh
     name="Curve001"
     castShadow
     receiveShadow
     geometry={nodes.Curve001.geometry}
     material={materials['React forground']}
     position={[-1.42385, -0.40575, -2.60113]}
     scale={4.09686}
    />
    <mesh
     name="Curve002"
     castShadow
     receiveShadow
     geometry={nodes.Curve002.geometry}
     material={materials['JS forground']}
     position={[0.12365, 0.36846, -2.01847]}
     scale={[3.92033, 1.40295, 3.92033]}
    />
    <mesh
     name="Curve003"
     castShadow
     receiveShadow
     geometry={nodes.Curve003.geometry}
     material={materials['JS forground']}
     position={[-0.12718, -0.43234, -2.01847]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-3.92033, -1.40295, -3.92033]}
    />
    <group
     name="Curve012"
     position={[-0.70139, 0.36725, -1.13816]}
     scale={[0.58202, 1.45142, 0.58202]}>
     <mesh
      name="Curve011_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve011_1.geometry}
      material={materials['Firebase 1']}
     />
     <mesh
      name="Curve011_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve011_2.geometry}
      material={materials['Firebase 3']}
     />
     <mesh
      name="Curve011_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve011_3.geometry}
      material={materials['Firebase 2']}
     />
    </group>
    <group
     name="Curve004"
     position={[-0.67408, -0.4017, -1.14139]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-0.58202, -1.45142, -0.58202]}>
     <mesh
      name="Curve012_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve012_1.geometry}
      material={materials['Firebase 1']}
     />
     <mesh
      name="Curve012_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve012_2.geometry}
      material={materials['Firebase 3']}
     />
     <mesh
      name="Curve012_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve012_3.geometry}
      material={materials['Firebase 2']}
     />
    </group>
    <mesh
     name="Curve005"
     castShadow
     receiveShadow
     geometry={nodes.Curve005.geometry}
     material={materials['Pure white']}
     position={[-0.21952, 0.36766, 0.25516]}
     scale={[3.40669, 1.86004, 3.40669]}
    />
    <mesh
     name="Curve006"
     castShadow
     receiveShadow
     geometry={nodes.Curve006.geometry}
     material={materials['Pure white']}
     position={[-0.55605, -0.43693, 0.2745]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-3.40669, -1.86004, -3.40669]}
    />
    <group
     name="Curve007"
     position={[1.07331, 0.36853, 0.31546]}
     scale={[2.82331, 1.83548, 2.82331]}>
     <mesh
      name="Curve015_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve015_1.geometry}
      material={materials['SVGMat.019']}
     />
     <mesh
      name="Curve015_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve015_2.geometry}
      material={materials['SVGMat.020']}
     />
     <mesh
      name="Curve015_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve015_3.geometry}
      material={materials['AWS forground']}
     />
    </group>
    <group
     name="Curve008"
     position={[1.03317, -0.43064, 0.3149]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-2.82331, -1.83548, -2.82331]}>
     <mesh
      name="Curve018_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve018_1.geometry}
      material={materials['SVGMat.019']}
     />
     <mesh
      name="Curve018_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve018_2.geometry}
      material={materials['SVGMat.020']}
     />
     <mesh
      name="Curve018_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve018_3.geometry}
      material={materials['AWS forground']}
     />
    </group>
    <mesh
     name="Curve009"
     castShadow
     receiveShadow
     geometry={nodes.Curve009.geometry}
     material={materials['Pure white']}
     position={[-0.06201, 0.368, 1.25905]}
     scale={[3.20535, 3.77051, 3.20535]}
    />
    <mesh
     name="Curve010"
     castShadow
     receiveShadow
     geometry={nodes.Curve010.geometry}
     material={materials['Pure white']}
     position={[-0.0787, -0.4336, 1.2594]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-3.20535, -3.77051, -3.20535]}
    />
    <group
     name="Curve014"
     position={[-1.79558, 0.40253, 2.54908]}
     scale={[2.43968, 3.5367, 2.43968]}>
     <mesh
      name="Curve023_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve023_1.geometry}
      material={materials['SVGMat.025']}
     />
     <mesh
      name="Curve023_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve023_2.geometry}
      material={materials['SVGMat.023']}
     />
     <mesh
      name="Curve023_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve023_3.geometry}
      material={materials['SVGMat.024']}
     />
    </group>
    <group
     name="Curve011"
     position={[-1.84241, -0.40208, 2.54638]}
     rotation={[0, 0, 3.14157]}
     scale={[2.43968, 3.5367, 2.43968]}>
     <mesh
      name="Curve024_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve024_1.geometry}
      material={materials['SVGMat.025']}
     />
     <mesh
      name="Curve024_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve024_2.geometry}
      material={materials['SVGMat.023']}
     />
     <mesh
      name="Curve024_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve024_3.geometry}
      material={materials['SVGMat.024']}
     />
    </group>
    <mesh
     name="Curve013"
     castShadow
     receiveShadow
     geometry={nodes.Curve013.geometry}
     material={materials['flutter sky blue']}
     position={[-1.68833, 0.36686, -0.43848]}
     scale={[0.95993, 0.72279, 0.95993]}
    />
    <mesh
     name="Curve015"
     castShadow
     receiveShadow
     geometry={nodes.Curve015.geometry}
     material={materials['flutter dark blue']}
     position={[-1.63167, 0.36686, -0.14007]}
     scale={[0.95993, 0.72279, 0.95993]}
    />
    <mesh
     name="Curve016"
     castShadow
     receiveShadow
     geometry={nodes.Curve016.geometry}
     material={materials['flutter medium blue']}
     position={[-1.74121, 0.36686, -0.24961]}
     scale={[0.95993, 0.72279, 0.95993]}
    />
    <mesh
     name="Curve018"
     castShadow
     receiveShadow
     geometry={nodes.Curve018.geometry}
     material={materials['flutter dark blue']}
     position={[-1.66613, 0.36686, -0.20468]}
     scale={[0.95993, 0.72279, 0.95993]}
    />
    <mesh
     name="Curve017"
     castShadow
     receiveShadow
     geometry={nodes.Curve017.geometry}
     material={materials['flutter medium blue.001']}
     position={[-1.63293, -0.43223, -0.24961]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-0.95993, -0.72279, -0.95993]}
    />
    <mesh
     name="Curve019"
     castShadow
     receiveShadow
     geometry={nodes.Curve019.geometry}
     material={materials['flutter dark blue.001']}
     position={[-1.74247, -0.43223, -0.14007]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-0.95993, -0.72279, -0.95993]}
    />
    <mesh
     name="Curve020"
     castShadow
     receiveShadow
     geometry={nodes.Curve020.geometry}
     material={materials['flutter sky blue.001']}
     position={[-1.68581, -0.43223, -0.43848]}
     rotation={[-Math.PI, 0, 0]}
     scale={[-0.95993, -0.72279, -0.95993]}
    />
    <group
     name="Curve021"
     position={[-1.44434, -0.40503, 1.07113]}
     rotation={[0, 0, 3.13993]}
     scale={[2.09372, 3.14627, 2.09372]}>
     <mesh
      name="Curve022_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve022_1.geometry}
      material={materials['CSS White.001']}
     />
     <mesh
      name="Curve022_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve022_2.geometry}
      material={materials['CSS color 2.001']}
     />
     <mesh
      name="Curve022_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve022_3.geometry}
      material={materials['CSS color 1.001']}
     />
    </group>
    <group
     name="Curve022"
     position={[0.54741, -0.39958, -0.64801]}
     rotation={[0, 0, -3.14078]}
     scale={[2.36319, 2.74012, 2.36319]}>
     <mesh
      name="Curve028_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve028_1.geometry}
      material={materials['Angular red 2.001']}
     />
     <mesh
      name="Curve028_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve028_2.geometry}
      material={materials['Angular red 1.001']}
     />
     <mesh
      name="Curve028_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve028_3.geometry}
      material={materials['Angular White.001']}
     />
    </group>
    <group
     name="Curve023"
     position={[-1.44434, 0.40126, 1.07113]}
     scale={[2.09372, 2.76573, 2.09372]}>
     <mesh
      name="Curve016_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve016_1.geometry}
      material={materials['CSS White']}
     />
     <mesh
      name="Curve016_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve016_2.geometry}
      material={materials['CSS color 2']}
     />
     <mesh
      name="Curve016_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve016_3.geometry}
      material={materials['CSS color 1']}
     />
    </group>
    <group
     name="Curve024"
     position={[0.61204, 0.40131, -0.62574]}
     scale={[2.36319, 2.74011, 2.36319]}>
     <mesh
      name="Curve026_1"
      castShadow
      receiveShadow
      geometry={nodes.Curve026_1.geometry}
      material={materials['Angular red 2']}
     />
     <mesh
      name="Curve026_2"
      castShadow
      receiveShadow
      geometry={nodes.Curve026_2.geometry}
      material={materials['Angular red 1']}
     />
     <mesh
      name="Curve026_3"
      castShadow
      receiveShadow
      geometry={nodes.Curve026_3.geometry}
      material={materials['Angular White']}
     />
    </group>
    <mesh
     name="Curve025"
     castShadow
     receiveShadow
     geometry={nodes.Curve025.geometry}
     material={materials['Material.001']}
     position={[0.42084, 0.39919, 2.54335]}
     scale={[2.87972, 2.54767, 2.87972]}
    />
    <mesh
     name="Curve026"
     castShadow
     receiveShadow
     geometry={nodes.Curve026.geometry}
     material={materials['Material.002']}
     position={[0.28159, -0.39842, 2.54335]}
     rotation={[0, 0, -3.14077]}
     scale={[2.87972, 2.54768, 2.87972]}
    />
    <mesh
     name="Curve027"
     castShadow
     receiveShadow
     geometry={nodes.Curve027.geometry}
     material={materials['React forground']}
     position={[-1.42176, 0.40642, -2.60113]}
     rotation={[0, 0, -0.0014]}
     scale={4.09686}
    />
    <mesh
     name="Cube011"
     castShadow
     receiveShadow
     geometry={nodes.Cube011.geometry}
     material={materials['Angular White']}
     position={[1.30494, 0, -1.89813]}
     scale={[0.38596, 0.36774, 0.38596]}
    />
    <mesh
     name="Cube012"
     castShadow
     receiveShadow
     geometry={nodes.Cube012.geometry}
     material={materials['Angular White']}
     position={[1.60494, 0, 1.60187]}
     scale={[0.38596, 0.36774, 0.38596]}
    />
    <mesh
     name="Curve"
     castShadow
     receiveShadow
     geometry={nodes.Curve.geometry}
     material={materials.Golang}
     position={[1.26952, 0.4, -1.91622]}
     scale={3.09974}
    />
    <mesh
     name="Curve028"
     castShadow
     receiveShadow
     geometry={nodes.Curve028.geometry}
     material={materials.Golang}
     position={[1.34952, -0.4, -1.91622]}
     rotation={[0, 0, Math.PI]}
     scale={3.09974}
    />
    <mesh
     name="Curve029"
     castShadow
     receiveShadow
     geometry={nodes.Curve029.geometry}
     material={materials.Nextjs}
     position={[1.64866, 0.4, 1.67533]}
     scale={[2.45506, 0.68136, 2.45506]}
    />
    <mesh
     name="Curve030"
     castShadow
     receiveShadow
     geometry={nodes.Curve030.geometry}
     material={materials.Nextjs}
     position={[1.58866, -0.4, 1.67533]}
     rotation={[0, 0, Math.PI]}
     scale={[2.45506, 0.68136, 2.45506]}
    />
   </group>
  </group>
 );
}

useGLTF.preload("/3d/intro-model.glb");